import { readFileSync, writeFileSync } from "node:fs";
// Regenerates src/data.generated.ts from the configured iconify collection.
// The collection is a dev dependency named in icons.config.json — swapping
// sets is a config edit and a rerun, never a runtime change.
import { createRequire } from "node:module";

import { getIconData } from "@iconify/utils";

const require = createRequire(import.meta.url);
const config = JSON.parse(readFileSync(new URL("../icons.config.json", import.meta.url), "utf8"));

const loaded = require(config.collection);
// Collection packages either export the IconifyJSON directly or wrap it in
// an `icons` payload — accept both shapes.
const collection =
  loaded.icons && loaded.icons.prefix && loaded.icons.icons ? loaded.icons : loaded;
const unknown = config.icons.filter((name) => !getIconData(collection, name));
if (unknown.length > 0) {
  console.error(`icons.config.json names missing from ${config.collection}: ${unknown.join(", ")}`);
  process.exit(1);
}

const entries = config.icons.map((name) => {
  const icon = getIconData(collection, name);
  return `export const ${name.replace(/-/g, "_")}: IconifyIcon = ${JSON.stringify(icon)};`;
});

const header = `// Generated by scripts/generate.mjs from ${config.collection} — iconify
// format, one export per glyph. Never edit; extend icons.config.json and
// rerun the generator.\nimport type { IconifyIcon } from "@iconify/types";\n\n`;
writeFileSync(
  new URL("../src/data.generated.ts", import.meta.url),
  header + entries.join("\n") + "\n",
);
console.log(
  `icons: ${config.icons.length} glyphs from ${config.collection} (prefix ${collection.prefix})`,
);
