import { readFileSync, writeFileSync } from "node:fs";
// Regenerates src/data.generated.ts from the collection named in
// icons.config.json. The package is the collection as named exports —
// the whole set, so a consumer that knows which glyph it wants imports
// that one name; bundlers shake the rest away. The collection package
// itself stays a dev dependency; swapping sets is a config edit and a
// rerun, never a runtime change.
import { createRequire } from "node:module";

import { getIconData } from "@iconify/utils";

const require = createRequire(import.meta.url);
const config = JSON.parse(readFileSync(new URL("../icons.config.json", import.meta.url), "utf8"));

const loaded = require(config.collection);
// Collection packages either export the IconifyJSON directly or wrap it in
// an `icons` payload — accept both shapes.
const collection =
  loaded.icons && loaded.icons.prefix && loaded.icons.icons ? loaded.icons : loaded;

// A module export cannot be a reserved word — lucide ships `delete` and
// `package`, so those exports get a trailing underscore.
const RESERVED = new Set([
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);
const exportName = (name) => {
  const id = name.replace(/-/g, "_");
  return RESERVED.has(id) ? id + "_" : id;
};

const everyName = [...Object.keys(collection.icons), ...Object.keys(collection.aliases ?? {})];
// Icons the collection marks hidden are deprecated names — they stay out
// of the door entirely, and the hidden flag itself is collection
// metadata, not part of the icon.
const entries = everyName
  .map((name) => ({ name, icon: getIconData(collection, name) }))
  .filter((entry) => entry.icon && entry.icon.hidden !== true)
  .map((entry) => {
    const { hidden: _hidden, ...shape } = entry.icon;
    return `export const ${exportName(entry.name)}: IconifyIcon = ${JSON.stringify(shape)};`;
  });

const header = `// Generated by scripts/generate-icons.mjs from ${config.collection} —
// iconify format, the whole collection as named exports. Never edit;
// rerun the generator.\nimport type { IconifyIcon } from "@iconify/types";\n\n`;
writeFileSync(
  new URL("../src/data.generated.ts", import.meta.url),
  header + entries.join("\n") + "\n",
);
console.log(
  `icons: ${entries.length} exports from ${config.collection} (prefix ${collection.prefix})`,
);
