/** The component families grouped by section — the same partition the
 * Storybook titles use (the ladder in the vue preview sorts identically),
 * so the shelves and the story sidebar never disagree. Every family the
 * generator can discover must appear exactly once; the generator fails
 * loudly on a miss or a duplicate. Sections list their families in file
 * order, mirroring componentOrder's byte-order rule. */

export const componentSections: Array<{
  slug: string;
  zh: string;
  en: string;
  families: string[];
}> = [
  {
    slug: "elements",
    zh: "基础元件",
    en: "Elements",
    families: [
      "avatar-group",
      "avatar",
      "badge",
      "button-group",
      "button",
      "card",
      "chip",
      "client-only",
      "config-provider",
      "format",
      "highlight",
      "icon",
      "kbd",
      "presence",
      "separator",
      "deferred-content",
      "user",
    ],
  },
  {
    slug: "actions",
    zh: "动作",
    en: "Actions",
    families: [
      "clipboard",
      "dock",
      "download-trigger",
      "float-button",
      "split-button",
      "swap",
      "toggle",
      "toggle-group",
      "toolbar",
    ],
  },
  {
    slug: "forms",
    zh: "表单",
    en: "Forms",
    families: [
      "angle-slider",
      "autocomplete",
      "calendar",
      "cascade-select",
      "checkbox-group",
      "checkbox",
      "color-picker",
      "combobox",
      "date-input",
      "date-picker",
      "dynamic-input",
      "editable",
      "field",
      "fieldset",
      "file-upload",
      "form",
      "input-group",
      "input",
      "listbox",
      "mentions",
      "number-input",
      "password-input",
      "pin-input",
      "radio-group",
      "rating-group",
      "segment-group",
      "select",
      "signature-pad",
      "slider",
      "switch",
      "tags-input",
      "textarea",
      "tree-select",
    ],
  },
  {
    slug: "navigation",
    zh: "导航",
    en: "Navigation",
    families: [
      "affix",
      "back-top",
      "breadcrumb",
      "link",
      "menubar",
      "navigation-menu",
      "pagination",
      "steps",
      "tabs",
      "toc",
    ],
  },
  {
    slug: "overlay",
    zh: "浮层",
    en: "Overlay",
    families: [
      "command",
      "dialog",
      "drawer",
      "floating-panel",
      "focus-trap",
      "hover-card",
      "menu",
      "popconfirm",
      "popover",
      "toast",
      "tooltip",
      "tour",
    ],
  },
  {
    slug: "data",
    zh: "数据",
    en: "Data",
    families: [
      "chart",
      "collection",
      "comment",
      "descriptions",
      "json-tree-view",
      "list",
      "stat",
      "table",
      "timeline",
      "timer",
      "transfer",
      "tree-view",
      "workflow",
      "data-view",
      "order-list",
      "terminal",
      "virtual-list",
    ],
  },
  {
    slug: "media",
    zh: "媒体",
    en: "Media",
    families: [
      "browser",
      "carousel",
      "image-cropper",
      "image-viewer",
      "image",
      "marquee",
      "media-player",
      "qr-code",
      "watermark",
    ],
  },
  {
    slug: "feedback",
    zh: "反馈",
    en: "Feedback",
    families: [
      "alert",
      "banner",
      "empty",
      "meter",
      "progress-group",
      "progress",
      "result",
      "skeleton",
      "spinner",
      "block-ui",
    ],
  },
  {
    slug: "layout",
    zh: "布局",
    en: "Layout",
    families: [
      "accordion",
      "bento",
      "aspect-ratio",
      "collapsible",
      "container",
      "ellipsis",
      "frame",
      "grid",
      "layout",
      "masonry",
      "page-header",
      "scroll-area",
      "splitter",
      "spotlight",
      "stack",
      "typography",
    ],
  },
  {
    slug: "ai",
    zh: "AI",
    en: "AI",
    families: [
      "ai",
      "ai-action",
      "ai-attachments",
      "ai-message",
      "ai-prompt-input",
      "ai-reasoning",
      "ai-response",
      "ai-source",
      "ai-suggestion",
      "ai-tool",
    ],
  },
];
