/** The Chinese name of every component family. One table, two consumers:
 * the docs generator writes it into the zh page titles, and the api-nav
 * plugin titles the sidebar's reference links with it. Keep it in family
 * order — the generator's page ordering follows the vue package. */
export const componentNames: Record<string, string> = {
  accordion: "手风琴",
  affix: "固钉",
  ai: "AI 会话",
  "ai-action": "AI 操作",
  "ai-attachments": "AI 附件",
  "ai-message": "AI 消息",
  "ai-prompt-input": "AI 提示输入",
  "ai-reasoning": "AI 思考",
  "ai-response": "AI 回复",
  "ai-source": "AI 来源",
  "ai-suggestion": "AI 建议",
  "ai-tool": "AI 工具调用",
  alert: "提醒",
  "angle-slider": "角度滑块",
  "aspect-ratio": "宽高比",
  autocomplete: "自动补全",
  avatar: "头像",
  "avatar-group": "头像组",
  "back-top": "回到顶部",
  badge: "徽标",
  banner: "横幅",
  breadcrumb: "面包屑",
  "button-group": "按钮组",
  button: "按钮",
  calendar: "日历",
  "cascade-select": "级联选择",
  card: "卡片",
  carousel: "走马灯",
  chart: "图表",
  checkbox: "复选框",
  "checkbox-group": "复选框组",
  chip: "角标",
  "client-only": "客户端渲染",
  clipboard: "剪贴板",
  collapsible: "折叠面板",
  collection: "集合",
  "color-picker": "颜色选择器",
  combobox: "组合框",
  comment: "评论",
  "config-provider": "全局配置",
  container: "容器",
  "date-input": "日期输入",
  "date-picker": "日期选择器",
  descriptions: "描述列表",
  dialog: "对话框",
  "download-trigger": "下载触发器",
  drawer: "抽屉",
  "dynamic-input": "动态输入",
  editable: "可编辑文本",
  ellipsis: "文本省略",
  empty: "空状态",
  form: "表单",
  field: "字段",
  fieldset: "字段组",
  "file-upload": "文件上传",
  "float-button": "悬浮按钮",
  "floating-panel": "悬浮面板",
  "focus-trap": "焦点陷阱",
  format: "格式化",
  frame: "画框",
  grid: "栅格",
  highlight: "高亮文本",
  "hover-card": "悬停卡片",
  icon: "图标",
  "image-cropper": "图片裁剪",
  "image-viewer": "图片查看器",
  image: "图片",
  "input-group": "输入框组",
  input: "输入框",
  "json-tree-view": "JSON 树视图",
  kbd: "按键",
  layout: "布局",
  link: "链接",
  list: "列表",
  listbox: "列表框",
  marquee: "滚动横幅",
  masonry: "瀑布流",
  menu: "菜单",
  mentions: "提及",
  menubar: "菜单栏",
  meter: "度量",
  "navigation-menu": "导航菜单",
  "number-input": "数字输入",
  "page-header": "页头",
  pagination: "分页",
  "password-input": "密码输入",
  "pin-input": "验证码输入",
  popconfirm: "气泡确认",
  popover: "气泡卡片",
  presence: "挂载过渡",
  "progress-group": "进度组",
  progress: "进度条",
  "qr-code": "二维码",
  "radio-group": "单选组",
  "rating-group": "评分",
  "scroll-area": "滚动区域",
  "segment-group": "分段控制器",
  select: "选择器",
  separator: "分隔线",
  "signature-pad": "签名板",
  skeleton: "骨架屏",
  slider: "滑块",
  spinner: "加载器",
  "split-button": "拆分按钮",
  splitter: "分栏面板",
  stack: "层叠布局",
  stat: "统计",
  steps: "步骤条",
  swap: "切换",
  switch: "开关",
  table: "表格",
  tabs: "标签页",
  "tags-input": "标签输入",
  textarea: "文本域",
  timeline: "时间线",
  timer: "计时器",
  toast: "全局提示",
  toc: "目录",
  toggle: "切换按钮",
  "toggle-group": "切换按钮组",
  tooltip: "文字提示",
  tour: "引导",
  transfer: "穿梭框",
  "tree-select": "树选择",
  "tree-view": "树形控件",
  typography: "排版",
  watermark: "水印",
};
