/** The component families grouped by section — the same partition the
 * Storybook titles use (the ladder in the vue preview sorts identically),
 * so the shelves and the story sidebar never disagree. Every family the
 * generator can discover must appear exactly once; the generator fails
 * loudly on a miss or a duplicate. Sections list their families in file
 * order, mirroring componentOrder's byte-order rule. */

export const componentSections: Array<{
  slug: string;
  zh: string;
  en: string;
  families: string[];
}> = [
  {
    slug: "elements",
    zh: "基础元件",
    en: "Elements",
    families: [
      "avatar-group",
      "avatar",
      "badge",
      "button",
      "card",
      "chip",
      "format",
      "highlight",
      "kbd",
      "separator",
    ],
  },
  {
    slug: "actions",
    zh: "动作",
    en: "Actions",
    families: ["clipboard", "swap", "toggle", "toggle-group"],
  },
  {
    slug: "forms",
    zh: "表单",
    en: "Forms",
    families: [
      "angle-slider",
      "autocomplete",
      "calendar",
      "cascade-select",
      "checkbox-group",
      "checkbox",
      "color-picker",
      "combobox",
      "date-input",
      "date-picker",
      "editable",
      "field",
      "fieldset",
      "file-upload",
      "form",
      "input",
      "listbox",
      "number-input",
      "password-input",
      "pin-input",
      "radio-group",
      "rating-group",
      "segment-group",
      "select",
      "signature-pad",
      "slider",
      "switch",
      "tags-input",
      "textarea",
      "tree-select",
    ],
  },
  {
    slug: "navigation",
    zh: "导航",
    en: "Navigation",
    families: ["breadcrumb", "link", "navigation-menu", "pagination", "steps", "tabs", "toc"],
  },
  {
    slug: "overlay",
    zh: "浮层",
    en: "Overlay",
    families: [
      "dialog",
      "drawer",
      "floating-panel",
      "hover-card",
      "menu",
      "popconfirm",
      "popover",
      "toast",
      "tooltip",
      "tour",
    ],
  },
  {
    slug: "data",
    zh: "数据",
    en: "Data",
    families: [
      "collection",
      "descriptions",
      "json-tree-view",
      "marquee",
      "stat",
      "table",
      "timeline",
      "timer",
      "transfer",
      "tree-view",
    ],
  },
  {
    slug: "media",
    zh: "媒体",
    en: "Media",
    families: ["carousel", "image-cropper", "qr-code"],
  },
  {
    slug: "feedback",
    zh: "反馈",
    en: "Feedback",
    families: ["alert", "banner", "meter", "progress", "skeleton", "spinner"],
  },
  {
    slug: "layout",
    zh: "布局",
    en: "Layout",
    families: [
      "accordion",
      "collapsible",
      "empty",
      "frame",
      "page-header",
      "scroll-area",
      "splitter",
      "typography",
    ],
  },
  {
    slug: "ai",
    zh: "AI",
    en: "AI",
    families: [
      "ai",
      "ai-action",
      "ai-message",
      "ai-prompt-input",
      "ai-reasoning",
      "ai-response",
      "ai-source",
      "ai-suggestion",
      "ai-tool",
    ],
  },
];
